version: '3.1'
services:
  quizzy_dotnetapi:
    container_name: quizzy_dotnetapi
    build: ./QuizzyAPI/QuizzyAPI/
    ports:
      - '5997:80'
    depends_on: 
      - 'quizzy_pgdb'
  quizzy_pgdb:
    container_name: quizzy_pgdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: quizzy
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - './data/pg:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
