version: '3.1'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: quizzy
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - './data/pg:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
